Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update]
  resources :games do
    resource :watches, only: [:create, :destroy]
    resource :excellents, only: [:create, :destroy]
    resource :goods, only: [:create, :destroy]
    resource :fairs, only: [:create, :destroy]
    resource :ungoods, only: [:create, :destroy]
    resource :bads, only: [:create, :destroy]
    resource :for_kids, only: [:create, :destroy]
    resource :for_teens, only: [:create, :destroy]
    resource :for_women, only: [:create, :destroy]
    resource :for_men, only: [:create, :destroy]
    resource :for_beginners, only: [:create, :destroy]
    resource :for_geeks, only: [:create, :destroy]
    resource :carefullies, only: [:create, :destroy]
    resource :excitements, only: [:create, :destroy]
    resource :two_p_can_enjoys, only: [:create, :destroy]
    resource :drunk_can_enjoys, only: [:create, :destroy]
    resource :for_singles_parties, only: [:create, :destroy]
    resource :with_friend_can_enjoys, only: [:create, :destroy]
    resource :light_weights, only: [:create, :destroy]
    resource :midlle_weights, only: [:create, :destroy]
    resource :super_midlle_weights, only: [:create, :destroy]
    resource :heavy_weights, only: [:create, :destroy]
    resource :super_heavy_weights, only: [:create, :destroy]
    resource :dices, only: [:create, :destroy]
    resource :buttings, only: [:create, :destroy]
    resource :actions, only: [:create, :destroy]
    resource :tile_placements, only: [:create, :destroy]
    resource :bluffs, only: [:create, :destroy]
    resource :hand_managements, only: [:create, :destroy]
    resource :set_collections, only: [:create, :destroy]
    resource :expanded_reproductions, only: [:create, :destroy]
    resource :worker_placements, only: [:create, :destroy]
    resource :trick_takings, only: [:create, :destroy]
    resource :partnerships, only: [:create, :destroy]
    resource :concealments, only: [:create, :destroy]
    resource :draftings, only: [:create, :destroy]
    resource :bursts, only: [:create, :destroy]
    resource :cooperations, only: [:create, :destroy]
    resource :negotiations, only: [:create, :destroy]
    resource :area_majorities, only: [:create, :destroy]
    resource :memories, only: [:create, :destroy]
    resource :repeats, only: [:create, :destroy]
    resource :studies, only: [:create, :destroy]
    resource :lucks, only: [:create, :destroy]
    resource :forces, only: [:create, :destroy]
    resource :balances, only: [:create, :destroy]
    resource :repeat_more_interestings, only: [:create, :destroy]
    resource :repeat_uninterestings, only: [:create, :destroy]
    resource :only_onces, only: [:create, :destroy]
    resource :long_waiting_times, only: [:create, :destroy]
    resource :easy_rules, only: [:create, :destroy]
    resource :easy_to_gets, only: [:create, :destroy]
    resource :many_expansions, only: [:create, :destroy]
  end
  root 'games#index'
  get 'about' => 'games#about'
end